apiVersion: v1
kind: Service
metadata:
  name: catalogd-webhook-service
  namespace: olmv1-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: catalogd-webhook

