apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogd-webhook-role
rules:
  - apiGroups:
      - catalogd.operatorframework.io
    resources:
      - clustercatalogs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["create", "patch", "delete"]